version: "3.9"

services:
  devopsdb:
    image: poornaavula1211/myfp:db
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 350M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - mydbvolume:/var/lib/postgresql/data
        
    

  application:
    image: poornaavula1211/myfp:app
    ports:
      - "1111:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 350M
        reservations:
          cpus: "0.25"
          memory: 64M
          
    depends_on:
      - devopsdb
      
volumes:
   mydbvolume:
  


